import path from "node:path";

/**
 * Every filesystem location the app reads, in one place.
 *
 * `data/` is provided input and treated as read-only: the roster, the guideline
 * corpus, the 27 evaluation briefs and their answer key. The tests read it
 * directly rather than through a copy, so there is one source of truth and no
 * possibility of a fixture silently drifting from the data the engine is
 * actually graded against.
 */

export const PROJECT_ROOT = process.cwd();

/** Provided source data. Read-only. */
export const DATA_DIR = path.join(PROJECT_ROOT, "data");
export const GUIDELINES_DIR = path.join(DATA_DIR, "guidelines");
export const BRIEFS_DIR = path.join(DATA_DIR, "briefs");
export const CLIENTS_FILE = path.join(DATA_DIR, "clients.json");
export const ANSWER_KEY_FILE = path.join(DATA_DIR, "answer_key.json");
export const AGENCY_STANDARDS_FILE = "00_agency_standards.md";

/** Runtime uploads. Gitignored -- generated by the app, not checked in. */
export const UPLOADS_DIR = path.join(PROJECT_ROOT, "public", "uploads");
export const MEDIA_UPLOADS_DIR = path.join(UPLOADS_DIR, "media");
export const REFERENCE_UPLOADS_DIR = path.join(UPLOADS_DIR, "references");

/** Where the Phase 12 evaluation writes its report. */
export const DOCS_DIR = path.join(PROJECT_ROOT, "docs");
export const EVALUATION_REPORT_FILE = path.join(DOCS_DIR, "evaluation.md");
