"use client";

import { useState } from "react";

import type { HistorySerialized } from "@/domain/regenerationHistory";

/**
 * Which reference produced which draft.
 *
 * Loaded when opened, not with the page. A history is two queries per item, and
 * a twenty-item list would spend forty of them filling panels nobody has
 * expanded -- the N+1 a list screen most easily grows.
 *
 * The panel is honest about what the product actually keeps. There are no stored
 * version snapshots: a `ContentItem` carries its current body and the audit trail
 * carries what happened to it. So a run is shown as an event -- when, by whom,
 * what it was prompted with, where the status moved -- rather than as a diff
 * against text that was never saved.
 *
 * References from a **refused** regeneration are shown separately rather than
 * dropped. Those runs store their attachments and then return without editing
 * anything, so no run claims them -- and a reference that produced a flagged
 * result is precisely the one a reviewer wants to look at.
 */
export function HistoryPanel({
  contentItemId,
  referenceCount,
}: {
  contentItemId: string;
  referenceCount: number;
}) {
  const [open, setOpen] = useState(false);
  const [history, setHistory] = useState<HistorySerialized | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function toggle() {
    if (open) {
      setOpen(false);
      return;
    }

    setOpen(true);

    // Fetched once per mount. Reopening a panel shows what was already loaded;
    // a regeneration in the meantime refreshes the page anyway, which remounts
    // this.
    if (history !== null) return;

    setBusy(true);
    setError(null);

    const response = await fetch(`/api/content-items/${contentItemId}/history`);

    if (!response.ok) {
      setError("Could not load the history.");
      setBusy(false);
      return;
    }

    setHistory((await response.json()) as HistorySerialized);
    setBusy(false);
  }

  const nothing =
    history !== null && history.runs.length === 0 && history.unattributed.length === 0;

  return (
    <div>
      <button
        type="button"
        onClick={toggle}
        aria-expanded={open}
        className="text-sm font-semibold text-body underline underline-offset-4 transition-colors hover:text-heading"
      >
        {referenceCount === 0
          ? "Regeneration history"
          : `Regeneration history · ${referenceCount} reference${referenceCount === 1 ? "" : "s"}`}
      </button>

      {open ? (
        <div className="mt-3">
          {busy ? <p className="text-sm text-body">Loading…</p> : null}

          {error ? (
            <p role="alert" className="rounded-lg bg-danger-bg px-3 py-2 text-sm text-danger">
              {error}
            </p>
          ) : null}

          {nothing ? (
            <p className="text-sm text-body">
              This item has not been regenerated. It is as the engine first drafted it.
            </p>
          ) : null}

          {history !== null && history.runs.length > 0 ? (
            <ol className="space-y-3">
              {history.runs.map((run) => (
                <li key={run.audit_id} className="rounded-xl border border-edge bg-canvas px-4 py-3">
                  <p className="text-sm font-semibold text-heading">
                    Regenerated by {run.performed_by_name ?? "someone"} ·{" "}
                    {new Date(run.performed_at).toLocaleString()}
                  </p>
                  {run.from_status && run.to_status ? (
                    <p className="mt-0.5 text-xs text-body/70">
                      {run.from_status} → {run.to_status}
                    </p>
                  ) : null}
                  <ReferenceList references={run.references} empty="Prompt only — no references." />
                </li>
              ))}
            </ol>
          ) : null}

          {history !== null && history.unattributed.length > 0 ? (
            <div className="mt-3 rounded-xl border border-flag/30 bg-flag-bg px-4 py-3">
              <p className="text-sm font-semibold text-flag">
                Attached, but no draft came from them
              </p>
              <p className="mt-0.5 text-xs text-body">
                The regeneration these were supplied for was refused, so the draft was
                left as it was. Kept on purpose — this is what produced that refusal.
              </p>
              <ReferenceList references={history.unattributed} empty="" />
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

function ReferenceList({
  references,
  empty,
}: {
  references: HistorySerialized["runs"][number]["references"];
  empty: string;
}) {
  if (references.length === 0) {
    return empty ? <p className="mt-2 text-sm text-body">{empty}</p> : null;
  }

  return (
    <ul className="mt-2 space-y-2">
      {references.map((reference) => (
        <li key={reference.attachment_id} className="flex items-start gap-3">
          {reference.file_type === "image" ? (
            /* A user upload of unknown dimensions, served from our own /public.
               next/image wants a width and height nothing here knows, and would
               run an optimiser over a file a creator is checking by eye. */
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={reference.public_url}
              alt={reference.instruction ?? "Reference image"}
              className="h-16 w-16 shrink-0 rounded-lg border border-edge object-cover"
            />
          ) : (
            <span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-lg border border-edge bg-surface text-xs font-semibold uppercase text-body">
              {reference.file_type}
            </span>
          )}

          <div className="min-w-0">
            <a
              href={reference.public_url}
              target="_blank"
              rel="noreferrer"
              className="text-sm font-semibold text-heading underline underline-offset-4"
            >
              Open reference
            </a>
            {reference.instruction ? (
              <p className="mt-0.5 text-sm text-body">“{reference.instruction}”</p>
            ) : (
              <p className="mt-0.5 text-sm text-body/70">No instruction given.</p>
            )}
            <p className="mt-0.5 text-xs text-body/70">
              {reference.uploaded_by_name ?? "Someone"} ·{" "}
              {new Date(reference.created_at).toLocaleString()}
            </p>
          </div>
        </li>
      ))}
    </ul>
  );
}
